Import('env lib deps compile_against PhonyTarget')

env.AppendUnique(CPPPATH = '#/../include')
env.AppendUnique(LIBPATH = '#/../lib')

compile_against(['cmocka'], deps, env)

env.PrependUnique(LIBS = 'meraxes')

for f in Glob('*.c'):
    test = env.Program(f)
    Depends(test, lib)

# Command('run_tests', 'tocf_test', '/usr/local/x86_64/gnu/openmpi-1.6.1/bin/mpirun -n 1 $SOURCE')

# PhonyTarget(env, run_tests = 'unbuffer /usr/local/x86_64/gnu/openmpi-1.6.1/bin/mpirun -n 4 valgrind tests/find_HII_bubbles_test 2>&1 | tee tests/dump.txt')
PhonyTarget(env, run_tests = '/usr/local/x86_64/gnu/openmpi-1.6.1/bin/mpirun -n 4 tests/find_HII_bubbles_test')
