# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget meraxes_lib mlog)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target meraxes_lib
add_library(meraxes_lib STATIC IMPORTED)

set_target_properties(meraxes_lib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/fred/oz025/yqin/bitbucket/meraxes/src/mlog;/apps/skylake/software/mpi/gcc/7.3.0/openmpi/3.0.0/hdf5/1.10.1/include;/apps/skylake/software/core/szip/2.1.1/include;/apps/skylake/software/core/binutils/2.30/include;/apps/skylake/software/mpi/gcc/7.3.0/openmpi/3.0.0/fftw/3.3.7/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:m>;MPI::MPI_C;mlog;\$<LINK_ONLY:GSL::gsl>;\$<LINK_ONLY:GSL::gslcblas>;/apps/skylake/software/mpi/gcc/7.3.0/openmpi/3.0.0/hdf5/1.10.1/lib/libhdf5.so;/apps/skylake/software/core/szip/2.1.1/lib/libsz.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;/usr/lib64/libpthread.so;/apps/skylake/software/mpi/gcc/7.3.0/openmpi/3.0.0/hdf5/1.10.1/lib/libhdf5_hl.so;/apps/skylake/software/mpi/gcc/7.3.0/openmpi/3.0.0/fftw/3.3.7/lib/libfftw3f_mpi.so;/apps/skylake/software/mpi/gcc/7.3.0/openmpi/3.0.0/fftw/3.3.7/lib/libfftw3f.so"
)

# Create imported target mlog
add_library(mlog STATIC IMPORTED)

set_target_properties(mlog PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:MPI::MPI_C>"
)

# Import target "meraxes_lib" for configuration ""
set_property(TARGET meraxes_lib APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(meraxes_lib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/fred/oz025/yqin/bitbucket/meraxes/src/lib/libmeraxes.a"
  )

# Import target "mlog" for configuration ""
set_property(TARGET mlog APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(mlog PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/fred/oz025/yqin/bitbucket/meraxes/src/lib/libmlog.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
